server:
  port: 5000

spring:
  main:
    web-application-type: servlet
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
dynamodb:
  access-key: AKIA3NCPY2JHR5NFIHNU
  endpoint: https://dynamodb.ap-southeast-2.amazonaws.com
  secret-key: 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