package org.whitestar.TimberDemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName="Request")
public class Request {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String postedBy;
    @DynamoDBAttribute
    private String acceptedBy;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String description;

    public Request(String id, String user_id, String title, String description) {
        this.id = id;
        this.postedBy = user_id;
        this.acceptedBy = null;
        this.title = title;
        this.description = description;
    }

    public Request(String user_id, String title, String description) {
        this.postedBy = user_id;
        this.acceptedBy = null;
        this.title = title;
        this.description = description;
    }
}