package org.whitestar.TimberDemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="Skill")
public class Skill {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBTypeConvertedJson
    private SkillType skillType;
}
