package org.whitestar.TimberDemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName="skilltable")
public class User_Skill {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String user_id;
    @DynamoDBAttribute
    private String skill_id;
    @DynamoDBAttribute
    private int level;
    @DynamoDBAttribute
    private int levelExperience;
    @DynamoDBAttribute
    //accumulated experience for current level
    private int currentExperience;

    public User_Skill(String id, String user_id, String skill_id) {
        this.id = id;
        this.user_id = user_id;
        this.skill_id = skill_id;
        this.level = 1;
        this.levelExperience = 100;
        this.currentExperience = 0;
    }

    public User_Skill(String user_id, String skill_id) {
        this.user_id = user_id;
        this.skill_id = skill_id;
        this.level = 1;
        this.levelExperience = 100;
        this.currentExperience = 0;
    }
}
