package org.whitestar.TimberDemo.entity;

import java.time.LocalDate;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="UserProfile")
public class UserProfile {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private String id;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private Integer age;
    @DynamoDBAttribute
    private String email;
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate dob;
    @DynamoDBAttribute
    private int level;
    @DynamoDBAttribute
    private int bounties;
    //experience required to level up for current level
    @DynamoDBAttribute
    private int levelExperience;
    //accumulated experience for current level
    @DynamoDBAttribute
    private int currentExperience;

    public UserProfile(String name, Integer age, String email, LocalDate dob) {
        this.name = name;
        this.age = age;
        this.email = email;
        this.dob = dob;
        this.level = 1;
        this.bounties = 0;
        this.levelExperience = 100;
        this.currentExperience = 20;
    }
}