package org.whitestar.TimberDemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName="userskilltable")
public class User_Skill {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String userId;
    @DynamoDBAttribute
    private String skillId;
    @DynamoDBAttribute
    private int level;
    @DynamoDBAttribute
    private int levelExperience;
    @DynamoDBAttribute
    //accumulated experience for current level
    private int currentExperience;

    public User_Skill(String id, String userId, String skillId) {
        this.id = id;
        this.userId = userId;
        this.skillId = skillId;
        this.level = 1;
        this.levelExperience = 100;
        this.currentExperience = 0;
    }

    public User_Skill(String userId, String skillId) {
        this.userId = userId;
        this.skillId = skillId;
        this.level = 1;
        this.levelExperience = 100;
        this.currentExperience = 0;
    }
}
